# Form implementation generated from reading ui file 'Anasayfa.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Anasayfa(object):
    def setupUi(self, Anasayfa):
        Anasayfa.setObjectName("Anasayfa")
        Anasayfa.resize(1006, 625)
        Anasayfa.setStyleSheet("background-color:#ddfeff;\n"
"font-size:14pt;\n"
"color: rgb(170, 0, 0);\n"
"font-weight:bold;")
        self.centralwidget = QtWidgets.QWidget(parent=Anasayfa)
        self.centralwidget.setObjectName("centralwidget")
        self.urun = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.urun.setGeometry(QtCore.QRect(0, 0, 751, 571))
        self.urun.setStyleSheet("background-color:#ddfeff;\n"
"color: rgb(170, 0, 255);\n"
"font-size:14pt;\n"
"font: 8pt \"Comic Sans MS\";\n"
"font-weight:bold;")
        self.urun.setObjectName("urun")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox.setGeometry(QtCore.QRect(-10, 0, 771, 521))
        self.groupBox.setMouseTracking(False)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.c1 = QtWidgets.QLabel(parent=self.groupBox)
        self.c1.setEnabled(True)
        self.c1.setGeometry(QtCore.QRect(60, 100, 191, 221))
        self.c1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.c1.setText("")
        self.c1.setPixmap(QtGui.QPixmap("C:/Users/Dell/.designer/backup/foto/1.jpg"))
        self.c1.setScaledContents(True)
        self.c1.setOpenExternalLinks(True)
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QLabel(parent=self.groupBox)
        self.c2.setGeometry(QtCore.QRect(290, 100, 191, 221))
        self.c2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.c2.setText("")
        self.c2.setPixmap(QtGui.QPixmap("C:/Users/Dell/.designer/backup/foto/2.jpg"))
        self.c2.setScaledContents(True)
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QLabel(parent=self.groupBox)
        self.c3.setGeometry(QtCore.QRect(520, 100, 191, 221))
        self.c3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.c3.setText("")
        self.c3.setPixmap(QtGui.QPixmap("C:/Users/Dell/.designer/backup/foto/3.jpg"))
        self.c3.setScaledContents(True)
        self.c3.setObjectName("c3")
        self.bs1 = QtWidgets.QPushButton(parent=self.groupBox)
        self.bs1.setGeometry(QtCore.QRect(120, 410, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bs1.setFont(font)
        self.bs1.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.bs1.setObjectName("bs1")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(70, 340, 161, 51))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(300, 340, 161, 51))
        self.label_5.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(530, 340, 161, 51))
        self.label_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.bs2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.bs2.setGeometry(QtCore.QRect(340, 410, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bs2.setFont(font)
        self.bs2.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.bs2.setObjectName("bs2")
        self.bs3 = QtWidgets.QPushButton(parent=self.groupBox)
        self.bs3.setGeometry(QtCore.QRect(570, 420, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bs3.setFont(font)
        self.bs3.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.bs3.setObjectName("bs3")
        self.urun.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(-10, 0, 771, 521))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.a1 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.a1.setGeometry(QtCore.QRect(60, 100, 191, 221))
        self.a1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.a1.setText("")
        self.a1.setPixmap(QtGui.QPixmap("C:/Users/Dell/.designer/backup/foto/4.jpg"))
        self.a1.setScaledContents(True)
        self.a1.setObjectName("a1")
        self.a2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.a2.setGeometry(QtCore.QRect(290, 100, 191, 221))
        self.a2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.a2.setText("")
        self.a2.setPixmap(QtGui.QPixmap("C:/Users/Dell/.designer/backup/foto/5.jpg"))
        self.a2.setScaledContents(True)
        self.a2.setObjectName("a2")
        self.a3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.a3.setGeometry(QtCore.QRect(520, 100, 191, 221))
        self.a3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.a3.setText("")
        self.a3.setPixmap(QtGui.QPixmap("C:/Users/Dell/.designer/backup/foto/6.jpg"))
        self.a3.setScaledContents(True)
        self.a3.setObjectName("a3")
        self.bs4 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.bs4.setGeometry(QtCore.QRect(120, 420, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bs4.setFont(font)
        self.bs4.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.bs4.setObjectName("bs4")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(70, 340, 161, 51))
        self.label_10.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(280, 320, 191, 31))
        self.label_11.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"text-decoration: line-through;\n"
"\n"
"\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(530, 340, 161, 51))
        self.label_12.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.bs5 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.bs5.setGeometry(QtCore.QRect(340, 420, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bs5.setFont(font)
        self.bs5.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.bs5.setObjectName("bs5")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(300, 350, 161, 41))
        self.label_13.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.bs5_2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.bs5_2.setGeometry(QtCore.QRect(570, 420, 61, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bs5_2.setFont(font)
        self.bs5_2.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.bs5_2.setObjectName("bs5_2")
        self.urun.addTab(self.tab_2, "")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(750, 180, 251, 371))
        self.tableWidget.setStyleSheet("font: 75 13pt \"MS Serif\";\n"
"color: rgb(0, 0, 127);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(759, 245, 101, 51))
        self.label_14.setStyleSheet("\n"
"font: 25 10pt \"Cascadia Code Light\";\n"
"\n"
"")
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(882, 245, 111, 51))
        self.label_15.setStyleSheet("\n"
"font: 25 10pt \"Cascadia Code Light\";\n"
"\n"
"")
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(883, 330, 111, 51))
        self.label_16.setStyleSheet("\n"
"font: 25 10pt \"Cascadia Code Light\";\n"
"\n"
"")
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(760, 330, 101, 51))
        self.label_17.setStyleSheet("\n"
"font: 25 10pt \"Cascadia Code Light\";\n"
"\n"
"")
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        Anasayfa.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Anasayfa)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 37))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(parent=self.menubar)
        self.menuMen.setObjectName("menuMen")
        self.menuH_sab_m = QtWidgets.QMenu(parent=self.menubar)
        self.menuH_sab_m.setObjectName("menuH_sab_m")
        Anasayfa.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Anasayfa)
        self.statusbar.setObjectName("statusbar")
        Anasayfa.setStatusBar(self.statusbar)
        self.actionKad_n = QtGui.QAction(parent=Anasayfa)
        self.actionKad_n.setObjectName("actionKad_n")
        self.actionErkek = QtGui.QAction(parent=Anasayfa)
        self.actionErkek.setObjectName("actionErkek")
        self.action_ocuk = QtGui.QAction(parent=Anasayfa)
        self.action_ocuk.setObjectName("action_ocuk")
        self.cikis = QtGui.QAction(parent=Anasayfa)
        self.cikis.setObjectName("cikis")
        self.Gris = QtGui.QAction(parent=Anasayfa)
        self.Gris.setObjectName("Gris")
        self.kayit = QtGui.QAction(parent=Anasayfa)
        self.kayit.setObjectName("kayit")
        self.actionsepet = QtGui.QAction(parent=Anasayfa)
        self.actionsepet.setObjectName("actionsepet")
        self.actionFavoriler = QtGui.QAction(parent=Anasayfa)
        self.actionFavoriler.setObjectName("actionFavoriler")
        self.sepet_2 = QtGui.QAction(parent=Anasayfa)
        self.sepet_2.setObjectName("sepet_2")
        self.menuMen.addSeparator()
        self.menuMen.addAction(self.cikis)
        self.menuH_sab_m.addAction(self.kayit)
        self.menubar.addAction(self.menuMen.menuAction())
        self.menubar.addAction(self.menuH_sab_m.menuAction())

        self.retranslateUi(Anasayfa)
        self.urun.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Anasayfa)

    def retranslateUi(self, Anasayfa):
        _translate = QtCore.QCoreApplication.translate
        Anasayfa.setWindowTitle(_translate("Anasayfa", "MainWindow"))
        self.bs1.setText(_translate("Anasayfa", "Sepete \n"
" ekle"))
        self.label_4.setText(_translate("Anasayfa", "470,50TL"))
        self.label_5.setText(_translate("Anasayfa", "690,95TL"))
        self.label_6.setText(_translate("Anasayfa", "450,95TL"))
        self.bs2.setText(_translate("Anasayfa", "Sepete \n"
" ekle"))
        self.bs3.setText(_translate("Anasayfa", "Sepete \n"
" ekle"))
        self.urun.setTabText(self.urun.indexOf(self.tab), _translate("Anasayfa", "Çanta"))
        self.bs4.setText(_translate("Anasayfa", "Sepete \n"
" ekle"))
        self.label_10.setText(_translate("Anasayfa", "550,20TL"))
        self.label_11.setText(_translate("Anasayfa", "1090TL"))
        self.label_12.setText(_translate("Anasayfa", "720,95TL"))
        self.bs5.setText(_translate("Anasayfa", "Sepete \n"
" ekle"))
        self.label_13.setText(_translate("Anasayfa", "920TL"))
        self.bs5_2.setText(_translate("Anasayfa", "Sepete \n"
" ekle"))
        self.urun.setTabText(self.urun.indexOf(self.tab_2), _translate("Anasayfa", "Ayakkabı"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Anasayfa", "Ürün"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Anasayfa", "Fiyat"))
        self.menuMen.setTitle(_translate("Anasayfa", "Menü"))
        self.menuH_sab_m.setTitle(_translate("Anasayfa", "Hısabım"))
        self.actionKad_n.setText(_translate("Anasayfa", "Kadın"))
        self.actionErkek.setText(_translate("Anasayfa", "Erkek"))
        self.action_ocuk.setText(_translate("Anasayfa", "Çocuk"))
        self.cikis.setText(_translate("Anasayfa", "Çıkış"))
        self.Gris.setText(_translate("Anasayfa", "Griş Yap"))
        self.kayit.setText(_translate("Anasayfa", "Kayıt "))
        self.actionsepet.setText(_translate("Anasayfa", "sepet"))
        self.actionFavoriler.setText(_translate("Anasayfa", "Favoriler"))
        self.sepet_2.setText(_translate("Anasayfa", "sepet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Anasayfa = QtWidgets.QMainWindow()
    ui = Ui_Anasayfa()
    ui.setupUi(Anasayfa)
    Anasayfa.show()
    sys.exit(app.exec())
