# Form implementation generated from reading ui file 'bilgi.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class bilgi_Form(object):
    def setupUi(self, Form_Ara):
        Form_Ara.setObjectName("Form_Ara")
        Form_Ara.resize(511, 294)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form_Ara)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 251, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.btn = QtWidgets.QPushButton(parent=Form_Ara)
        self.btn.setGeometry(QtCore.QRect(300, 20, 91, 31))
        self.btn.setObjectName("btn")
        self.btn2 = QtWidgets.QPushButton(parent=Form_Ara)
        self.btn2.setGeometry(QtCore.QRect(410, 20, 91, 31))
        self.btn2.setObjectName("btn2")
        self.txt_adi = QtWidgets.QLineEdit(parent=Form_Ara)
        self.txt_adi.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.txt_adi.setObjectName("txt_adi")

        self.retranslateUi(Form_Ara)
        QtCore.QMetaObject.connectSlotsByName(Form_Ara)

    def retranslateUi(self, Form_Ara):
        _translate = QtCore.QCoreApplication.translate
        Form_Ara.setWindowTitle(_translate("Form_Ara", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form_Ara", "ADI"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form_Ara", "E_MAIL"))
        self.btn.setText(_translate("Form_Ara", "GÜNCELLE"))
        self.btn2.setText(_translate("Form_Ara", "SIL"))
        self.txt_adi.setPlaceholderText(_translate("Form_Ara", "E_MIL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Ara = QtWidgets.QWidget()
    ui = bilgi_Form()
    ui.setupUi(Form_Ara)
    Form_Ara.show()
    sys.exit(app.exec())
