# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(593, 496)
        self.Gris = QtWidgets.QGroupBox(parent=Form)
        self.Gris.setGeometry(QtCore.QRect(-20, 0, 771, 521))
        self.Gris.setStyleSheet("background-color: rgb(255, 205, 255);\n"
"font: 75 28pt \"MS Shell Dlg 2\";")
        self.Gris.setObjectName("Gris")
        self.label = QtWidgets.QLabel(parent=self.Gris)
        self.label.setGeometry(QtCore.QRect(80, 110, 101, 81))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.b_g_g = QtWidgets.QPushButton(parent=self.Gris)
        self.b_g_g.setGeometry(QtCore.QRect(200, 310, 91, 31))
        self.b_g_g.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.b_g_g.setObjectName("b_g_g")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.Gris)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 360, 121, 31))
        self.pushButton_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.Gris)
        self.lineEdit.setGeometry(QtCore.QRect(190, 130, 341, 41))
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.Gris)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 230, 341, 41))
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(parent=self.Gris)
        self.label_2.setGeometry(QtCore.QRect(80, 210, 101, 81))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.Gris)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 310, 121, 31))
        self.pushButton_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Gris.setTitle(_translate("Form", "                  Griş"))
        self.label.setText(_translate("Form", "E-mail :"))
        self.b_g_g.setText(_translate("Form", "Giriş yap"))
        self.pushButton_2.setText(_translate("Form", "Şifreyi unuttum"))
        self.lineEdit.setPlaceholderText(_translate("Form", "   E-mail"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "  Şifre"))
        self.label_2.setText(_translate("Form", "Şifre :"))
        self.pushButton_3.setText(_translate("Form", "Güncelle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
