# Form implementation generated from reading ui file 'kayit.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class kayit_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 489)
        self.kayit = QtWidgets.QGroupBox(parent=Form)
        self.kayit.setGeometry(QtCore.QRect(-20, 0, 771, 521))
        self.kayit.setStyleSheet("background-color: rgb(255, 205, 255);\n"
"font: 75 28pt \"MS Shell Dlg 2\";")
        self.kayit.setObjectName("kayit")
        self.label = QtWidgets.QLabel(parent=self.kayit)
        self.label.setGeometry(QtCore.QRect(80, 70, 101, 81))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.b_k_g = QtWidgets.QPushButton(parent=self.kayit)
        self.b_k_g.setGeometry(QtCore.QRect(380, 310, 101, 31))
        self.b_k_g.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.b_k_g.setObjectName("b_k_g")
        self.b_k_uye = QtWidgets.QPushButton(parent=self.kayit)
        self.b_k_uye.setGeometry(QtCore.QRect(220, 310, 101, 31))
        self.b_k_uye.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.b_k_uye.setObjectName("b_k_uye")
        self.k_email = QtWidgets.QLineEdit(parent=self.kayit)
        self.k_email.setGeometry(QtCore.QRect(190, 90, 341, 41))
        self.k_email.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.k_email.setObjectName("k_email")
        self.k_sifre = QtWidgets.QLineEdit(parent=self.kayit)
        self.k_sifre.setGeometry(QtCore.QRect(190, 230, 341, 41))
        self.k_sifre.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.k_sifre.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.k_sifre.setObjectName("k_sifre")
        self.label_2 = QtWidgets.QLabel(parent=self.kayit)
        self.label_2.setGeometry(QtCore.QRect(80, 210, 101, 81))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.adi = QtWidgets.QLineEdit(parent=self.kayit)
        self.adi.setGeometry(QtCore.QRect(190, 160, 341, 41))
        self.adi.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.adi.setObjectName("adi")
        self.label_3 = QtWidgets.QLabel(parent=self.kayit)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 101, 81))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.kayit)
        self.label_4.setGeometry(QtCore.QRect(80, 140, 101, 81))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.kayit.setTitle(_translate("Form", "                 Kayıt"))
        self.label.setText(_translate("Form", "E-mail :"))
        self.b_k_g.setText(_translate("Form", "Giriş yap"))
        self.b_k_uye.setText(_translate("Form", "Üye Ol"))
        self.k_email.setPlaceholderText(_translate("Form", "   E-mail"))
        self.k_sifre.setPlaceholderText(_translate("Form", "  Şifre"))
        self.label_2.setText(_translate("Form", "Şifre :"))
        self.adi.setPlaceholderText(_translate("Form", "   Adi"))
        self.label_3.setText(_translate("Form", "Şifre :"))
        self.label_4.setText(_translate("Form", "ADi :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = kayit_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
