# Form implementation generated from reading ui file 'arama.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Ara(object):
    def setupUi(self, Form_Ara):
        Form_Ara.setObjectName("Form_Ara")
        Form_Ara.resize(718, 379)
        self.tableWidget = QtWidgets.QTableWidget(Form_Ara)
        self.tableWidget.setGeometry(QtCore.QRect(60, 90, 531, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.comboBox_ara = QtWidgets.QComboBox(Form_Ara)
        self.comboBox_ara.setGeometry(QtCore.QRect(70, 20, 281, 31))
        self.comboBox_ara.setObjectName("comboBox_ara")
        self.btn_yenile = QtWidgets.QPushButton(Form_Ara)
        self.btn_yenile.setGeometry(QtCore.QRect(370, 20, 91, 31))
        self.btn_yenile.setObjectName("btn_yenile")
        self.btn_ara = QtWidgets.QPushButton(Form_Ara)
        self.btn_ara.setGeometry(QtCore.QRect(480, 20, 91, 31))
        self.btn_ara.setObjectName("btn_ara")

        self.retranslateUi(Form_Ara)
        QtCore.QMetaObject.connectSlotsByName(Form_Ara)

    def retranslateUi(self, Form_Ara):
        _translate = QtCore.QCoreApplication.translate
        Form_Ara.setWindowTitle(_translate("Form_Ara", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form_Ara", "IDNO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form_Ara", "ADI"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form_Ara", "YIL"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form_Ara", "SAYFA"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form_Ara", "DILI"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form_Ara", "YAYINEVI"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form_Ara", "ACIKLAMA"))
        self.btn_yenile.setText(_translate("Form_Ara", "YENILE"))
        self.btn_ara.setText(_translate("Form_Ara", "ARA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Ara = QtWidgets.QWidget()
    ui = Ui_Form_Ara()
    ui.setupUi(Form_Ara)
    Form_Ara.show()
    sys.exit(app.exec())
