# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 528)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.btn_konus = QtWidgets.QPushButton(Form)
        self.btn_konus.setGeometry(QtCore.QRect(60, 40, 151, 31))
        self.btn_konus.setObjectName("btn_konus")
        self.btn_yazdir = QtWidgets.QPushButton(Form)
        self.btn_yazdir.setGeometry(QtCore.QRect(220, 40, 151, 31))
        self.btn_yazdir.setObjectName("btn_yazdir")
        self.btn_websitesi = QtWidgets.QPushButton(Form)
        self.btn_websitesi.setGeometry(QtCore.QRect(60, 80, 151, 31))
        self.btn_websitesi.setObjectName("btn_websitesi")
        self.btn_mail = QtWidgets.QPushButton(Form)
        self.btn_mail.setGeometry(QtCore.QRect(220, 80, 151, 31))
        self.btn_mail.setObjectName("btn_mail")
        self.txt_gonderen = QtWidgets.QLineEdit(Form)
        self.txt_gonderen.setGeometry(QtCore.QRect(150, 150, 231, 31))
        self.txt_gonderen.setReadOnly(True)
        self.txt_gonderen.setObjectName("txt_gonderen")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(46, 150, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 190, 81, 20))
        self.label_2.setObjectName("label_2")
        self.txt_alici = QtWidgets.QLineEdit(Form)
        self.txt_alici.setGeometry(QtCore.QRect(150, 190, 231, 31))
        self.txt_alici.setObjectName("txt_alici")
        self.txt_konu = QtWidgets.QLineEdit(Form)
        self.txt_konu.setGeometry(QtCore.QRect(150, 230, 231, 31))
        self.txt_konu.setObjectName("txt_konu")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 230, 81, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 81, 20))
        self.label_4.setObjectName("label_4")
        self.txt_mesaj = QtWidgets.QPlainTextEdit(Form)
        self.txt_mesaj.setGeometry(QtCore.QRect(150, 270, 231, 151))
        self.txt_mesaj.setObjectName("txt_mesaj")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_konus.setText(_translate("Form", "Konuşmaya Başla"))
        self.btn_yazdir.setText(_translate("Form", "Yazdır"))
        self.btn_websitesi.setText(_translate("Form", "Web Sitesini Aç"))
        self.btn_mail.setText(_translate("Form", "Mail Gönder"))
        self.txt_gonderen.setText(_translate("Form", "sercantirmik@gmail.com"))
        self.label.setText(_translate("Form", "Gönderen:"))
        self.label_2.setText(_translate("Form", "Alıcı"))
        self.label_3.setText(_translate("Form", "Konu"))
        self.label_4.setText(_translate("Form", "Mesajınız:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
